model_name = "t5-base"
learning_rate = 8e-5 #hyperparam
max_length_input = 512
doTruncate = True
doPadding = "max_length"
split_train_test = .8
split_train_val = .95
batch_size = 16 #hyperparam
epochs = 6 #hyperparam
freeze_threshold = -1 #hyperparam